# Use a Python base image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /usr/src/app/

# Port the application runs on
EXPOSE 8001

# Command to run the Django development server
# IMPORTANT: It must run on 0.0.0.0 and on the EXPOSEd port
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]